import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from '@/components/custom/navbar/header'
import Footer from '@/components/custom/footer/footer'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import { dir } from 'i18next'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Dr Nurulina',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  // todo: move colors to it's variable and replace it everywhere
  const { locale } = await params

  return (
    <html lang={locale} dir={dir(locale)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#3d4a6e] antialiased`}
      >
        <div className='flex min-h-screen flex-col'>
          <Header />
          <main className='lg:px-[calc(50%-600px) mx-auto w-full max-w-screen-xl flex-1 grow px-4 pt-4 md:px-6 lg:px-8'>
            {children}
          </main>
          <TailwindIndicator />
          <Footer />
        </div>
      </body>
    </html>
  )
}
