import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
// import { Navbar } from '@/components/custom/navigation/Navbar'
import Footer from '@/components/custom/footer/Footer'
import Header from '@/components/custom/navbar/header'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import { dir } from 'i18next'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Dr Nurulina',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  const { locale } = await params
  return (
    <html lang={locale} dir={dir(locale)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='flex h-screen w-full flex-col'>
          {/* <Navbar /> */}
          <Header />
          <main className='container mx-auto mt-4 w-full flex-1 grow'>
            {children}
          </main>
          <TailwindIndicator />
          <Footer />
        </div>
      </body>
    </html>
  )
}
